//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace M_hmw.CIService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CIService.CIServiceSoap")]
    public interface CIServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetYourName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetYourName(string strYourName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetYourName", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetYourNameAsync(string strYourName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConsignAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_hmw.CIService.GetConsignAllResponse GetConsignAll(M_hmw.CIService.GetConsignAllRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConsignAll", ReplyAction="*")]
        System.Threading.Tasks.Task<M_hmw.CIService.GetConsignAllResponse> GetConsignAllAsync(M_hmw.CIService.GetConsignAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConsignAllD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_hmw.CIService.GetConsignAllDResponse GetConsignAllD(M_hmw.CIService.GetConsignAllDRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConsignAllD", ReplyAction="*")]
        System.Threading.Tasks.Task<M_hmw.CIService.GetConsignAllDResponse> GetConsignAllDAsync(M_hmw.CIService.GetConsignAllDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConsignAllC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_hmw.CIService.GetConsignAllCResponse GetConsignAllC(M_hmw.CIService.GetConsignAllCRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConsignAllC", ReplyAction="*")]
        System.Threading.Tasks.Task<M_hmw.CIService.GetConsignAllCResponse> GetConsignAllCAsync(M_hmw.CIService.GetConsignAllCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConsignSingle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_hmw.CIService.GetConsignSingleResponse GetConsignSingle(M_hmw.CIService.GetConsignSingleRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConsignSingle", ReplyAction="*")]
        System.Threading.Tasks.Task<M_hmw.CIService.GetConsignSingleResponse> GetConsignSingleAsync(M_hmw.CIService.GetConsignSingleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetParas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_hmw.CIService.GetParasResponse GetParas(M_hmw.CIService.GetParasRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetParas", ReplyAction="*")]
        System.Threading.Tasks.Task<M_hmw.CIService.GetParasResponse> GetParasAsync(M_hmw.CIService.GetParasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlterParas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="strErr")]
        string AlterParas(string strUser, string strPW, string strDelay, string strInterval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlterParas", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="strErr")]
        System.Threading.Tasks.Task<string> AlterParasAsync(string strUser, string strPW, string strDelay, string strInterval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConsignParas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_hmw.CIService.GetConsignParasResponse GetConsignParas(M_hmw.CIService.GetConsignParasRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConsignParas", ReplyAction="*")]
        System.Threading.Tasks.Task<M_hmw.CIService.GetConsignParasResponse> GetConsignParasAsync(M_hmw.CIService.GetConsignParasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlterConsignParas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="strErr")]
        string AlterConsignParas(string strUser, string strPW, string strCGNo, string strDelay, string strInterval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlterConsignParas", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="strErr")]
        System.Threading.Tasks.Task<string> AlterConsignParasAsync(string strUser, string strPW, string strCGNo, string strDelay, string strInterval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BatchPass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="strErr")]
        string BatchPass(string strUser, string strPW, string[] strTermParas, string[] strParas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BatchPass", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="strErr")]
        System.Threading.Tasks.Task<string> BatchPassAsync(string strUser, string strPW, string[] strTermParas, string[] strParas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConsignState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_hmw.CIService.GetConsignStateResponse GetConsignState(M_hmw.CIService.GetConsignStateRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConsignState", ReplyAction="*")]
        System.Threading.Tasks.Task<M_hmw.CIService.GetConsignStateResponse> GetConsignStateAsync(M_hmw.CIService.GetConsignStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlterConsignState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="strErr")]
        string AlterConsignState(string strUser, string strPW, string strCGNo, string strNewState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlterConsignState", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="strErr")]
        System.Threading.Tasks.Task<string> AlterConsignStateAsync(string strUser, string strPW, string strCGNo, string strNewState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConsignStates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_hmw.CIService.GetConsignStatesResponse GetConsignStates(M_hmw.CIService.GetConsignStatesRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConsignStates", ReplyAction="*")]
        System.Threading.Tasks.Task<M_hmw.CIService.GetConsignStatesResponse> GetConsignStatesAsync(M_hmw.CIService.GetConsignStatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlterConsignStates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="strErr")]
        string AlterConsignStates(string strUser, string strPW, string[] strCGNos, string strNewState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlterConsignStates", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="strErr")]
        System.Threading.Tasks.Task<string> AlterConsignStatesAsync(string strUser, string strPW, string[] strCGNos, string strNewState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttestWait", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_hmw.CIService.GetAttestWaitResponse GetAttestWait(M_hmw.CIService.GetAttestWaitRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttestWait", ReplyAction="*")]
        System.Threading.Tasks.Task<M_hmw.CIService.GetAttestWaitResponse> GetAttestWaitAsync(M_hmw.CIService.GetAttestWaitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttestPassNotBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_hmw.CIService.GetAttestPassNotBalanceResponse GetAttestPassNotBalance(M_hmw.CIService.GetAttestPassNotBalanceRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttestPassNotBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<M_hmw.CIService.GetAttestPassNotBalanceResponse> GetAttestPassNotBalanceAsync(M_hmw.CIService.GetAttestPassNotBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttestSelfBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_hmw.CIService.GetAttestSelfBalanceResponse GetAttestSelfBalance(M_hmw.CIService.GetAttestSelfBalanceRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttestSelfBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<M_hmw.CIService.GetAttestSelfBalanceResponse> GetAttestSelfBalanceAsync(M_hmw.CIService.GetAttestSelfBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttestFullBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_hmw.CIService.GetAttestFullBalanceResponse GetAttestFullBalance(M_hmw.CIService.GetAttestFullBalanceRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttestFullBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<M_hmw.CIService.GetAttestFullBalanceResponse> GetAttestFullBalanceAsync(M_hmw.CIService.GetAttestFullBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttestWait2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_hmw.CIService.GetAttestWait2Response GetAttestWait2(M_hmw.CIService.GetAttestWait2Request request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttestWait2", ReplyAction="*")]
        System.Threading.Tasks.Task<M_hmw.CIService.GetAttestWait2Response> GetAttestWait2Async(M_hmw.CIService.GetAttestWait2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttestNoPass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_hmw.CIService.GetAttestNoPassResponse GetAttestNoPass(M_hmw.CIService.GetAttestNoPassRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttestNoPass", ReplyAction="*")]
        System.Threading.Tasks.Task<M_hmw.CIService.GetAttestNoPassResponse> GetAttestNoPassAsync(M_hmw.CIService.GetAttestNoPassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttestFinish", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_hmw.CIService.GetAttestFinishResponse GetAttestFinish(M_hmw.CIService.GetAttestFinishRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttestFinish", ReplyAction="*")]
        System.Threading.Tasks.Task<M_hmw.CIService.GetAttestFinishResponse> GetAttestFinishAsync(M_hmw.CIService.GetAttestFinishRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetXlqBillGoods", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_hmw.CIService.GetXlqBillGoodsResponse GetXlqBillGoods(M_hmw.CIService.GetXlqBillGoodsRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetXlqBillGoods", ReplyAction="*")]
        System.Threading.Tasks.Task<M_hmw.CIService.GetXlqBillGoodsResponse> GetXlqBillGoodsAsync(M_hmw.CIService.GetXlqBillGoodsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetXlqEntrust", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_hmw.CIService.GetXlqEntrustResponse GetXlqEntrust(M_hmw.CIService.GetXlqEntrustRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetXlqEntrust", ReplyAction="*")]
        System.Threading.Tasks.Task<M_hmw.CIService.GetXlqEntrustResponse> GetXlqEntrustAsync(M_hmw.CIService.GetXlqEntrustRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlterXlqSys", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="strErr")]
        string AlterXlqSys(string strUser, string strPW, System.Data.DataTable dtBillGoods, string[] strParas, string strCGNo, string strCargoNo, string strNewState, string strOldState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlterXlqSys", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="strErr")]
        System.Threading.Tasks.Task<string> AlterXlqSysAsync(string strUser, string strPW, System.Data.DataTable dtBillGoods, string[] strParas, string strCGNo, string strCargoNo, string strNewState, string strOldState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLedStaticInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_hmw.CIService.GetLedStaticInfoResponse GetLedStaticInfo(M_hmw.CIService.GetLedStaticInfoRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLedStaticInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<M_hmw.CIService.GetLedStaticInfoResponse> GetLedStaticInfoAsync(M_hmw.CIService.GetLedStaticInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateLedStaticInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="strErr")]
        string UpdateLedStaticInfo(string strCodeDept, string strUser, string strPW, string strNewLedInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateLedStaticInfo", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="strErr")]
        System.Threading.Tasks.Task<string> UpdateLedStaticInfoAsync(string strCodeDept, string strUser, string strPW, string strNewLedInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWorkDriver", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        M_hmw.CIService.GetWorkDriverResponse GetWorkDriver(M_hmw.CIService.GetWorkDriverRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWorkDriver", ReplyAction="*")]
        System.Threading.Tasks.Task<M_hmw.CIService.GetWorkDriverResponse> GetWorkDriverAsync(M_hmw.CIService.GetWorkDriverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWorkDriver", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="strErr")]
        string UpdateWorkDriver(string strUser, string strPW, System.Data.DataTable dtDriver);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWorkDriver", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="strErr")]
        System.Threading.Tasks.Task<string> UpdateWorkDriverAsync(string strUser, string strPW, System.Data.DataTable dtDriver);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConsignAll", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetConsignAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strPW;
        
        public GetConsignAllRequest() {
        }
        
        public GetConsignAllRequest(string strUser, string strPW) {
            this.strUser = strUser;
            this.strPW = strPW;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConsignAllResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetConsignAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string xmlData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErr;
        
        public GetConsignAllResponse() {
        }
        
        public GetConsignAllResponse(string xmlData, string strErr) {
            this.xmlData = xmlData;
            this.strErr = strErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConsignAllD", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetConsignAllDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strPW;
        
        public GetConsignAllDRequest() {
        }
        
        public GetConsignAllDRequest(string strUser, string strPW) {
            this.strUser = strUser;
            this.strPW = strPW;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConsignAllDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetConsignAllDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable GetConsignAllDResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErr;
        
        public GetConsignAllDResponse() {
        }
        
        public GetConsignAllDResponse(System.Data.DataTable GetConsignAllDResult, string strErr) {
            this.GetConsignAllDResult = GetConsignAllDResult;
            this.strErr = strErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConsignAllC", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetConsignAllCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strPW;
        
        public GetConsignAllCRequest() {
        }
        
        public GetConsignAllCRequest(string strUser, string strPW) {
            this.strUser = strUser;
            this.strPW = strPW;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConsignAllCResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetConsignAllCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable GetConsignAllCResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErr;
        
        public GetConsignAllCResponse() {
        }
        
        public GetConsignAllCResponse(System.Data.DataTable GetConsignAllCResult, string strErr) {
            this.GetConsignAllCResult = GetConsignAllCResult;
            this.strErr = strErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConsignSingle", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetConsignSingleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strCGNo;
        
        public GetConsignSingleRequest() {
        }
        
        public GetConsignSingleRequest(string strUser, string strPW, string strCGNo) {
            this.strUser = strUser;
            this.strPW = strPW;
            this.strCGNo = strCGNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConsignSingleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetConsignSingleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string xmlData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErr;
        
        public GetConsignSingleResponse() {
        }
        
        public GetConsignSingleResponse(string xmlData, string strErr) {
            this.xmlData = xmlData;
            this.strErr = strErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetParas", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetParasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strPW;
        
        public GetParasRequest() {
        }
        
        public GetParasRequest(string strUser, string strPW) {
            this.strUser = strUser;
            this.strPW = strPW;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetParasResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetParasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strDelay;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strInterval;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strErr;
        
        public GetParasResponse() {
        }
        
        public GetParasResponse(string strDelay, string strInterval, string strErr) {
            this.strDelay = strDelay;
            this.strInterval = strInterval;
            this.strErr = strErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConsignParas", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetConsignParasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strCGNo;
        
        public GetConsignParasRequest() {
        }
        
        public GetConsignParasRequest(string strUser, string strPW, string strCGNo) {
            this.strUser = strUser;
            this.strPW = strPW;
            this.strCGNo = strCGNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConsignParasResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetConsignParasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strDelay;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strInterval;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strErr;
        
        public GetConsignParasResponse() {
        }
        
        public GetConsignParasResponse(string strDelay, string strInterval, string strErr) {
            this.strDelay = strDelay;
            this.strInterval = strInterval;
            this.strErr = strErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConsignState", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetConsignStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strCGNo;
        
        public GetConsignStateRequest() {
        }
        
        public GetConsignStateRequest(string strUser, string strPW, string strCGNo) {
            this.strUser = strUser;
            this.strPW = strPW;
            this.strCGNo = strCGNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConsignStateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetConsignStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetConsignStateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErr;
        
        public GetConsignStateResponse() {
        }
        
        public GetConsignStateResponse(string GetConsignStateResult, string strErr) {
            this.GetConsignStateResult = GetConsignStateResult;
            this.strErr = strErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConsignStates", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetConsignStatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] strCGNos;
        
        public GetConsignStatesRequest() {
        }
        
        public GetConsignStatesRequest(string strUser, string strPW, string[] strCGNos) {
            this.strUser = strUser;
            this.strPW = strPW;
            this.strCGNos = strCGNos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetConsignStatesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetConsignStatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] GetConsignStatesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErr;
        
        public GetConsignStatesResponse() {
        }
        
        public GetConsignStatesResponse(string[] GetConsignStatesResult, string strErr) {
            this.GetConsignStatesResult = GetConsignStatesResult;
            this.strErr = strErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAttestWait", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAttestWaitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strCGNo;
        
        public GetAttestWaitRequest() {
        }
        
        public GetAttestWaitRequest(string strUser, string strPW, string strCGNo) {
            this.strUser = strUser;
            this.strPW = strPW;
            this.strCGNo = strCGNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAttestWaitResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAttestWaitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable GetAttestWaitResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErr;
        
        public GetAttestWaitResponse() {
        }
        
        public GetAttestWaitResponse(System.Data.DataTable GetAttestWaitResult, string strErr) {
            this.GetAttestWaitResult = GetAttestWaitResult;
            this.strErr = strErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAttestPassNotBalance", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAttestPassNotBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strCGNo;
        
        public GetAttestPassNotBalanceRequest() {
        }
        
        public GetAttestPassNotBalanceRequest(string strUser, string strPW, string strCGNo) {
            this.strUser = strUser;
            this.strPW = strPW;
            this.strCGNo = strCGNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAttestPassNotBalanceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAttestPassNotBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable GetAttestPassNotBalanceResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErr;
        
        public GetAttestPassNotBalanceResponse() {
        }
        
        public GetAttestPassNotBalanceResponse(System.Data.DataTable GetAttestPassNotBalanceResult, string strErr) {
            this.GetAttestPassNotBalanceResult = GetAttestPassNotBalanceResult;
            this.strErr = strErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAttestSelfBalance", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAttestSelfBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strCGNo;
        
        public GetAttestSelfBalanceRequest() {
        }
        
        public GetAttestSelfBalanceRequest(string strUser, string strPW, string strCGNo) {
            this.strUser = strUser;
            this.strPW = strPW;
            this.strCGNo = strCGNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAttestSelfBalanceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAttestSelfBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable GetAttestSelfBalanceResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErr;
        
        public GetAttestSelfBalanceResponse() {
        }
        
        public GetAttestSelfBalanceResponse(System.Data.DataTable GetAttestSelfBalanceResult, string strErr) {
            this.GetAttestSelfBalanceResult = GetAttestSelfBalanceResult;
            this.strErr = strErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAttestFullBalance", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAttestFullBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strCGNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strBegin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string strEnd;
        
        public GetAttestFullBalanceRequest() {
        }
        
        public GetAttestFullBalanceRequest(string strUser, string strPW, string strCGNo, string strBegin, string strEnd) {
            this.strUser = strUser;
            this.strPW = strPW;
            this.strCGNo = strCGNo;
            this.strBegin = strBegin;
            this.strEnd = strEnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAttestFullBalanceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAttestFullBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable GetAttestFullBalanceResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErr;
        
        public GetAttestFullBalanceResponse() {
        }
        
        public GetAttestFullBalanceResponse(System.Data.DataTable GetAttestFullBalanceResult, string strErr) {
            this.GetAttestFullBalanceResult = GetAttestFullBalanceResult;
            this.strErr = strErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAttestWait2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAttestWait2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strCodeAgent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strCGNo;
        
        public GetAttestWait2Request() {
        }
        
        public GetAttestWait2Request(string strUser, string strPW, string strCodeAgent, string strCGNo) {
            this.strUser = strUser;
            this.strPW = strPW;
            this.strCodeAgent = strCodeAgent;
            this.strCGNo = strCGNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAttestWait2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAttestWait2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable GetAttestWait2Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErr;
        
        public GetAttestWait2Response() {
        }
        
        public GetAttestWait2Response(System.Data.DataTable GetAttestWait2Result, string strErr) {
            this.GetAttestWait2Result = GetAttestWait2Result;
            this.strErr = strErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAttestNoPass", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAttestNoPassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strCodeDepartMent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strCodeAgent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string strCGNo;
        
        public GetAttestNoPassRequest() {
        }
        
        public GetAttestNoPassRequest(string strUser, string strPW, string strCodeDepartMent, string strCodeAgent, string strCGNo) {
            this.strUser = strUser;
            this.strPW = strPW;
            this.strCodeDepartMent = strCodeDepartMent;
            this.strCodeAgent = strCodeAgent;
            this.strCGNo = strCGNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAttestNoPassResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAttestNoPassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable GetAttestNoPassResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErr;
        
        public GetAttestNoPassResponse() {
        }
        
        public GetAttestNoPassResponse(System.Data.DataTable GetAttestNoPassResult, string strErr) {
            this.GetAttestNoPassResult = GetAttestNoPassResult;
            this.strErr = strErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAttestFinish", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAttestFinishRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strCodeDepartMent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strCodeAgent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string strCGNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string strBeginDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string strEndDate;
        
        public GetAttestFinishRequest() {
        }
        
        public GetAttestFinishRequest(string strUser, string strPW, string strCodeDepartMent, string strCodeAgent, string strCGNo, string strBeginDate, string strEndDate) {
            this.strUser = strUser;
            this.strPW = strPW;
            this.strCodeDepartMent = strCodeDepartMent;
            this.strCodeAgent = strCodeAgent;
            this.strCGNo = strCGNo;
            this.strBeginDate = strBeginDate;
            this.strEndDate = strEndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAttestFinishResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAttestFinishResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable GetAttestFinishResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErr;
        
        public GetAttestFinishResponse() {
        }
        
        public GetAttestFinishResponse(System.Data.DataTable GetAttestFinishResult, string strErr) {
            this.GetAttestFinishResult = GetAttestFinishResult;
            this.strErr = strErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXlqBillGoods", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetXlqBillGoodsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strTerm;
        
        public GetXlqBillGoodsRequest() {
        }
        
        public GetXlqBillGoodsRequest(string strUser, string strPW, string strTerm) {
            this.strUser = strUser;
            this.strPW = strPW;
            this.strTerm = strTerm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXlqBillGoodsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetXlqBillGoodsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable GetXlqBillGoodsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErr;
        
        public GetXlqBillGoodsResponse() {
        }
        
        public GetXlqBillGoodsResponse(System.Data.DataTable GetXlqBillGoodsResult, string strErr) {
            this.GetXlqBillGoodsResult = GetXlqBillGoodsResult;
            this.strErr = strErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXlqEntrust", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetXlqEntrustRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strPW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strTerm;
        
        public GetXlqEntrustRequest() {
        }
        
        public GetXlqEntrustRequest(string strUser, string strPW, string strTerm) {
            this.strUser = strUser;
            this.strPW = strPW;
            this.strTerm = strTerm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXlqEntrustResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetXlqEntrustResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable GetXlqEntrustResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErr;
        
        public GetXlqEntrustResponse() {
        }
        
        public GetXlqEntrustResponse(System.Data.DataTable GetXlqEntrustResult, string strErr) {
            this.GetXlqEntrustResult = GetXlqEntrustResult;
            this.strErr = strErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLedStaticInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLedStaticInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strCodeDept;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strPW;
        
        public GetLedStaticInfoRequest() {
        }
        
        public GetLedStaticInfoRequest(string strCodeDept, string strUser, string strPW) {
            this.strCodeDept = strCodeDept;
            this.strUser = strUser;
            this.strPW = strPW;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLedStaticInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLedStaticInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetLedStaticInfoResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErr;
        
        public GetLedStaticInfoResponse() {
        }
        
        public GetLedStaticInfoResponse(string GetLedStaticInfoResult, string strErr) {
            this.GetLedStaticInfoResult = GetLedStaticInfoResult;
            this.strErr = strErr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWorkDriver", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetWorkDriverRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strCodeDept;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strPW;
        
        public GetWorkDriverRequest() {
        }
        
        public GetWorkDriverRequest(string strCodeDept, string strUser, string strPW) {
            this.strCodeDept = strCodeDept;
            this.strUser = strUser;
            this.strPW = strPW;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWorkDriverResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetWorkDriverResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable GetWorkDriverResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErr;
        
        public GetWorkDriverResponse() {
        }
        
        public GetWorkDriverResponse(System.Data.DataTable GetWorkDriverResult, string strErr) {
            this.GetWorkDriverResult = GetWorkDriverResult;
            this.strErr = strErr;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CIServiceSoapChannel : M_hmw.CIService.CIServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CIServiceSoapClient : System.ServiceModel.ClientBase<M_hmw.CIService.CIServiceSoap>, M_hmw.CIService.CIServiceSoap {
        
        public CIServiceSoapClient() {
        }
        
        public CIServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CIServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string GetYourName(string strYourName) {
            return base.Channel.GetYourName(strYourName);
        }
        
        public System.Threading.Tasks.Task<string> GetYourNameAsync(string strYourName) {
            return base.Channel.GetYourNameAsync(strYourName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_hmw.CIService.GetConsignAllResponse M_hmw.CIService.CIServiceSoap.GetConsignAll(M_hmw.CIService.GetConsignAllRequest request) {
            return base.Channel.GetConsignAll(request);
        }
        
        public string GetConsignAll(string strUser, string strPW, out string strErr) {
            M_hmw.CIService.GetConsignAllRequest inValue = new M_hmw.CIService.GetConsignAllRequest();
            inValue.strUser = strUser;
            inValue.strPW = strPW;
            M_hmw.CIService.GetConsignAllResponse retVal = ((M_hmw.CIService.CIServiceSoap)(this)).GetConsignAll(inValue);
            strErr = retVal.strErr;
            return retVal.xmlData;
        }
        
        public System.Threading.Tasks.Task<M_hmw.CIService.GetConsignAllResponse> GetConsignAllAsync(M_hmw.CIService.GetConsignAllRequest request) {
            return base.Channel.GetConsignAllAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_hmw.CIService.GetConsignAllDResponse M_hmw.CIService.CIServiceSoap.GetConsignAllD(M_hmw.CIService.GetConsignAllDRequest request) {
            return base.Channel.GetConsignAllD(request);
        }
        
        public System.Data.DataTable GetConsignAllD(string strUser, string strPW, out string strErr) {
            M_hmw.CIService.GetConsignAllDRequest inValue = new M_hmw.CIService.GetConsignAllDRequest();
            inValue.strUser = strUser;
            inValue.strPW = strPW;
            M_hmw.CIService.GetConsignAllDResponse retVal = ((M_hmw.CIService.CIServiceSoap)(this)).GetConsignAllD(inValue);
            strErr = retVal.strErr;
            return retVal.GetConsignAllDResult;
        }
        
        public System.Threading.Tasks.Task<M_hmw.CIService.GetConsignAllDResponse> GetConsignAllDAsync(M_hmw.CIService.GetConsignAllDRequest request) {
            return base.Channel.GetConsignAllDAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_hmw.CIService.GetConsignAllCResponse M_hmw.CIService.CIServiceSoap.GetConsignAllC(M_hmw.CIService.GetConsignAllCRequest request) {
            return base.Channel.GetConsignAllC(request);
        }
        
        public System.Data.DataTable GetConsignAllC(string strUser, string strPW, out string strErr) {
            M_hmw.CIService.GetConsignAllCRequest inValue = new M_hmw.CIService.GetConsignAllCRequest();
            inValue.strUser = strUser;
            inValue.strPW = strPW;
            M_hmw.CIService.GetConsignAllCResponse retVal = ((M_hmw.CIService.CIServiceSoap)(this)).GetConsignAllC(inValue);
            strErr = retVal.strErr;
            return retVal.GetConsignAllCResult;
        }
        
        public System.Threading.Tasks.Task<M_hmw.CIService.GetConsignAllCResponse> GetConsignAllCAsync(M_hmw.CIService.GetConsignAllCRequest request) {
            return base.Channel.GetConsignAllCAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_hmw.CIService.GetConsignSingleResponse M_hmw.CIService.CIServiceSoap.GetConsignSingle(M_hmw.CIService.GetConsignSingleRequest request) {
            return base.Channel.GetConsignSingle(request);
        }
        
        public string GetConsignSingle(string strUser, string strPW, string strCGNo, out string strErr) {
            M_hmw.CIService.GetConsignSingleRequest inValue = new M_hmw.CIService.GetConsignSingleRequest();
            inValue.strUser = strUser;
            inValue.strPW = strPW;
            inValue.strCGNo = strCGNo;
            M_hmw.CIService.GetConsignSingleResponse retVal = ((M_hmw.CIService.CIServiceSoap)(this)).GetConsignSingle(inValue);
            strErr = retVal.strErr;
            return retVal.xmlData;
        }
        
        public System.Threading.Tasks.Task<M_hmw.CIService.GetConsignSingleResponse> GetConsignSingleAsync(M_hmw.CIService.GetConsignSingleRequest request) {
            return base.Channel.GetConsignSingleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_hmw.CIService.GetParasResponse M_hmw.CIService.CIServiceSoap.GetParas(M_hmw.CIService.GetParasRequest request) {
            return base.Channel.GetParas(request);
        }
        
        public string GetParas(string strUser, string strPW, out string strInterval, out string strErr) {
            M_hmw.CIService.GetParasRequest inValue = new M_hmw.CIService.GetParasRequest();
            inValue.strUser = strUser;
            inValue.strPW = strPW;
            M_hmw.CIService.GetParasResponse retVal = ((M_hmw.CIService.CIServiceSoap)(this)).GetParas(inValue);
            strInterval = retVal.strInterval;
            strErr = retVal.strErr;
            return retVal.strDelay;
        }
        
        public System.Threading.Tasks.Task<M_hmw.CIService.GetParasResponse> GetParasAsync(M_hmw.CIService.GetParasRequest request) {
            return base.Channel.GetParasAsync(request);
        }
        
        public string AlterParas(string strUser, string strPW, string strDelay, string strInterval) {
            return base.Channel.AlterParas(strUser, strPW, strDelay, strInterval);
        }
        
        public System.Threading.Tasks.Task<string> AlterParasAsync(string strUser, string strPW, string strDelay, string strInterval) {
            return base.Channel.AlterParasAsync(strUser, strPW, strDelay, strInterval);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_hmw.CIService.GetConsignParasResponse M_hmw.CIService.CIServiceSoap.GetConsignParas(M_hmw.CIService.GetConsignParasRequest request) {
            return base.Channel.GetConsignParas(request);
        }
        
        public string GetConsignParas(string strUser, string strPW, string strCGNo, out string strInterval, out string strErr) {
            M_hmw.CIService.GetConsignParasRequest inValue = new M_hmw.CIService.GetConsignParasRequest();
            inValue.strUser = strUser;
            inValue.strPW = strPW;
            inValue.strCGNo = strCGNo;
            M_hmw.CIService.GetConsignParasResponse retVal = ((M_hmw.CIService.CIServiceSoap)(this)).GetConsignParas(inValue);
            strInterval = retVal.strInterval;
            strErr = retVal.strErr;
            return retVal.strDelay;
        }
        
        public System.Threading.Tasks.Task<M_hmw.CIService.GetConsignParasResponse> GetConsignParasAsync(M_hmw.CIService.GetConsignParasRequest request) {
            return base.Channel.GetConsignParasAsync(request);
        }
        
        public string AlterConsignParas(string strUser, string strPW, string strCGNo, string strDelay, string strInterval) {
            return base.Channel.AlterConsignParas(strUser, strPW, strCGNo, strDelay, strInterval);
        }
        
        public System.Threading.Tasks.Task<string> AlterConsignParasAsync(string strUser, string strPW, string strCGNo, string strDelay, string strInterval) {
            return base.Channel.AlterConsignParasAsync(strUser, strPW, strCGNo, strDelay, strInterval);
        }
        
        public string BatchPass(string strUser, string strPW, string[] strTermParas, string[] strParas) {
            return base.Channel.BatchPass(strUser, strPW, strTermParas, strParas);
        }
        
        public System.Threading.Tasks.Task<string> BatchPassAsync(string strUser, string strPW, string[] strTermParas, string[] strParas) {
            return base.Channel.BatchPassAsync(strUser, strPW, strTermParas, strParas);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_hmw.CIService.GetConsignStateResponse M_hmw.CIService.CIServiceSoap.GetConsignState(M_hmw.CIService.GetConsignStateRequest request) {
            return base.Channel.GetConsignState(request);
        }
        
        public string GetConsignState(string strUser, string strPW, string strCGNo, out string strErr) {
            M_hmw.CIService.GetConsignStateRequest inValue = new M_hmw.CIService.GetConsignStateRequest();
            inValue.strUser = strUser;
            inValue.strPW = strPW;
            inValue.strCGNo = strCGNo;
            M_hmw.CIService.GetConsignStateResponse retVal = ((M_hmw.CIService.CIServiceSoap)(this)).GetConsignState(inValue);
            strErr = retVal.strErr;
            return retVal.GetConsignStateResult;
        }
        
        public System.Threading.Tasks.Task<M_hmw.CIService.GetConsignStateResponse> GetConsignStateAsync(M_hmw.CIService.GetConsignStateRequest request) {
            return base.Channel.GetConsignStateAsync(request);
        }
        
        public string AlterConsignState(string strUser, string strPW, string strCGNo, string strNewState) {
            return base.Channel.AlterConsignState(strUser, strPW, strCGNo, strNewState);
        }
        
        public System.Threading.Tasks.Task<string> AlterConsignStateAsync(string strUser, string strPW, string strCGNo, string strNewState) {
            return base.Channel.AlterConsignStateAsync(strUser, strPW, strCGNo, strNewState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_hmw.CIService.GetConsignStatesResponse M_hmw.CIService.CIServiceSoap.GetConsignStates(M_hmw.CIService.GetConsignStatesRequest request) {
            return base.Channel.GetConsignStates(request);
        }
        
        public string[] GetConsignStates(string strUser, string strPW, string[] strCGNos, out string strErr) {
            M_hmw.CIService.GetConsignStatesRequest inValue = new M_hmw.CIService.GetConsignStatesRequest();
            inValue.strUser = strUser;
            inValue.strPW = strPW;
            inValue.strCGNos = strCGNos;
            M_hmw.CIService.GetConsignStatesResponse retVal = ((M_hmw.CIService.CIServiceSoap)(this)).GetConsignStates(inValue);
            strErr = retVal.strErr;
            return retVal.GetConsignStatesResult;
        }
        
        public System.Threading.Tasks.Task<M_hmw.CIService.GetConsignStatesResponse> GetConsignStatesAsync(M_hmw.CIService.GetConsignStatesRequest request) {
            return base.Channel.GetConsignStatesAsync(request);
        }
        
        public string AlterConsignStates(string strUser, string strPW, string[] strCGNos, string strNewState) {
            return base.Channel.AlterConsignStates(strUser, strPW, strCGNos, strNewState);
        }
        
        public System.Threading.Tasks.Task<string> AlterConsignStatesAsync(string strUser, string strPW, string[] strCGNos, string strNewState) {
            return base.Channel.AlterConsignStatesAsync(strUser, strPW, strCGNos, strNewState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_hmw.CIService.GetAttestWaitResponse M_hmw.CIService.CIServiceSoap.GetAttestWait(M_hmw.CIService.GetAttestWaitRequest request) {
            return base.Channel.GetAttestWait(request);
        }
        
        public System.Data.DataTable GetAttestWait(string strUser, string strPW, string strCGNo, out string strErr) {
            M_hmw.CIService.GetAttestWaitRequest inValue = new M_hmw.CIService.GetAttestWaitRequest();
            inValue.strUser = strUser;
            inValue.strPW = strPW;
            inValue.strCGNo = strCGNo;
            M_hmw.CIService.GetAttestWaitResponse retVal = ((M_hmw.CIService.CIServiceSoap)(this)).GetAttestWait(inValue);
            strErr = retVal.strErr;
            return retVal.GetAttestWaitResult;
        }
        
        public System.Threading.Tasks.Task<M_hmw.CIService.GetAttestWaitResponse> GetAttestWaitAsync(M_hmw.CIService.GetAttestWaitRequest request) {
            return base.Channel.GetAttestWaitAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_hmw.CIService.GetAttestPassNotBalanceResponse M_hmw.CIService.CIServiceSoap.GetAttestPassNotBalance(M_hmw.CIService.GetAttestPassNotBalanceRequest request) {
            return base.Channel.GetAttestPassNotBalance(request);
        }
        
        public System.Data.DataTable GetAttestPassNotBalance(string strUser, string strPW, string strCGNo, out string strErr) {
            M_hmw.CIService.GetAttestPassNotBalanceRequest inValue = new M_hmw.CIService.GetAttestPassNotBalanceRequest();
            inValue.strUser = strUser;
            inValue.strPW = strPW;
            inValue.strCGNo = strCGNo;
            M_hmw.CIService.GetAttestPassNotBalanceResponse retVal = ((M_hmw.CIService.CIServiceSoap)(this)).GetAttestPassNotBalance(inValue);
            strErr = retVal.strErr;
            return retVal.GetAttestPassNotBalanceResult;
        }
        
        public System.Threading.Tasks.Task<M_hmw.CIService.GetAttestPassNotBalanceResponse> GetAttestPassNotBalanceAsync(M_hmw.CIService.GetAttestPassNotBalanceRequest request) {
            return base.Channel.GetAttestPassNotBalanceAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_hmw.CIService.GetAttestSelfBalanceResponse M_hmw.CIService.CIServiceSoap.GetAttestSelfBalance(M_hmw.CIService.GetAttestSelfBalanceRequest request) {
            return base.Channel.GetAttestSelfBalance(request);
        }
        
        public System.Data.DataTable GetAttestSelfBalance(string strUser, string strPW, string strCGNo, out string strErr) {
            M_hmw.CIService.GetAttestSelfBalanceRequest inValue = new M_hmw.CIService.GetAttestSelfBalanceRequest();
            inValue.strUser = strUser;
            inValue.strPW = strPW;
            inValue.strCGNo = strCGNo;
            M_hmw.CIService.GetAttestSelfBalanceResponse retVal = ((M_hmw.CIService.CIServiceSoap)(this)).GetAttestSelfBalance(inValue);
            strErr = retVal.strErr;
            return retVal.GetAttestSelfBalanceResult;
        }
        
        public System.Threading.Tasks.Task<M_hmw.CIService.GetAttestSelfBalanceResponse> GetAttestSelfBalanceAsync(M_hmw.CIService.GetAttestSelfBalanceRequest request) {
            return base.Channel.GetAttestSelfBalanceAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_hmw.CIService.GetAttestFullBalanceResponse M_hmw.CIService.CIServiceSoap.GetAttestFullBalance(M_hmw.CIService.GetAttestFullBalanceRequest request) {
            return base.Channel.GetAttestFullBalance(request);
        }
        
        public System.Data.DataTable GetAttestFullBalance(string strUser, string strPW, string strCGNo, string strBegin, string strEnd, out string strErr) {
            M_hmw.CIService.GetAttestFullBalanceRequest inValue = new M_hmw.CIService.GetAttestFullBalanceRequest();
            inValue.strUser = strUser;
            inValue.strPW = strPW;
            inValue.strCGNo = strCGNo;
            inValue.strBegin = strBegin;
            inValue.strEnd = strEnd;
            M_hmw.CIService.GetAttestFullBalanceResponse retVal = ((M_hmw.CIService.CIServiceSoap)(this)).GetAttestFullBalance(inValue);
            strErr = retVal.strErr;
            return retVal.GetAttestFullBalanceResult;
        }
        
        public System.Threading.Tasks.Task<M_hmw.CIService.GetAttestFullBalanceResponse> GetAttestFullBalanceAsync(M_hmw.CIService.GetAttestFullBalanceRequest request) {
            return base.Channel.GetAttestFullBalanceAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_hmw.CIService.GetAttestWait2Response M_hmw.CIService.CIServiceSoap.GetAttestWait2(M_hmw.CIService.GetAttestWait2Request request) {
            return base.Channel.GetAttestWait2(request);
        }
        
        public System.Data.DataTable GetAttestWait2(string strUser, string strPW, string strCodeAgent, string strCGNo, out string strErr) {
            M_hmw.CIService.GetAttestWait2Request inValue = new M_hmw.CIService.GetAttestWait2Request();
            inValue.strUser = strUser;
            inValue.strPW = strPW;
            inValue.strCodeAgent = strCodeAgent;
            inValue.strCGNo = strCGNo;
            M_hmw.CIService.GetAttestWait2Response retVal = ((M_hmw.CIService.CIServiceSoap)(this)).GetAttestWait2(inValue);
            strErr = retVal.strErr;
            return retVal.GetAttestWait2Result;
        }
        
        public System.Threading.Tasks.Task<M_hmw.CIService.GetAttestWait2Response> GetAttestWait2Async(M_hmw.CIService.GetAttestWait2Request request) {
            return base.Channel.GetAttestWait2Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_hmw.CIService.GetAttestNoPassResponse M_hmw.CIService.CIServiceSoap.GetAttestNoPass(M_hmw.CIService.GetAttestNoPassRequest request) {
            return base.Channel.GetAttestNoPass(request);
        }
        
        public System.Data.DataTable GetAttestNoPass(string strUser, string strPW, string strCodeDepartMent, string strCodeAgent, string strCGNo, out string strErr) {
            M_hmw.CIService.GetAttestNoPassRequest inValue = new M_hmw.CIService.GetAttestNoPassRequest();
            inValue.strUser = strUser;
            inValue.strPW = strPW;
            inValue.strCodeDepartMent = strCodeDepartMent;
            inValue.strCodeAgent = strCodeAgent;
            inValue.strCGNo = strCGNo;
            M_hmw.CIService.GetAttestNoPassResponse retVal = ((M_hmw.CIService.CIServiceSoap)(this)).GetAttestNoPass(inValue);
            strErr = retVal.strErr;
            return retVal.GetAttestNoPassResult;
        }
        
        public System.Threading.Tasks.Task<M_hmw.CIService.GetAttestNoPassResponse> GetAttestNoPassAsync(M_hmw.CIService.GetAttestNoPassRequest request) {
            return base.Channel.GetAttestNoPassAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_hmw.CIService.GetAttestFinishResponse M_hmw.CIService.CIServiceSoap.GetAttestFinish(M_hmw.CIService.GetAttestFinishRequest request) {
            return base.Channel.GetAttestFinish(request);
        }
        
        public System.Data.DataTable GetAttestFinish(string strUser, string strPW, string strCodeDepartMent, string strCodeAgent, string strCGNo, string strBeginDate, string strEndDate, out string strErr) {
            M_hmw.CIService.GetAttestFinishRequest inValue = new M_hmw.CIService.GetAttestFinishRequest();
            inValue.strUser = strUser;
            inValue.strPW = strPW;
            inValue.strCodeDepartMent = strCodeDepartMent;
            inValue.strCodeAgent = strCodeAgent;
            inValue.strCGNo = strCGNo;
            inValue.strBeginDate = strBeginDate;
            inValue.strEndDate = strEndDate;
            M_hmw.CIService.GetAttestFinishResponse retVal = ((M_hmw.CIService.CIServiceSoap)(this)).GetAttestFinish(inValue);
            strErr = retVal.strErr;
            return retVal.GetAttestFinishResult;
        }
        
        public System.Threading.Tasks.Task<M_hmw.CIService.GetAttestFinishResponse> GetAttestFinishAsync(M_hmw.CIService.GetAttestFinishRequest request) {
            return base.Channel.GetAttestFinishAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_hmw.CIService.GetXlqBillGoodsResponse M_hmw.CIService.CIServiceSoap.GetXlqBillGoods(M_hmw.CIService.GetXlqBillGoodsRequest request) {
            return base.Channel.GetXlqBillGoods(request);
        }
        
        public System.Data.DataTable GetXlqBillGoods(string strUser, string strPW, string strTerm, out string strErr) {
            M_hmw.CIService.GetXlqBillGoodsRequest inValue = new M_hmw.CIService.GetXlqBillGoodsRequest();
            inValue.strUser = strUser;
            inValue.strPW = strPW;
            inValue.strTerm = strTerm;
            M_hmw.CIService.GetXlqBillGoodsResponse retVal = ((M_hmw.CIService.CIServiceSoap)(this)).GetXlqBillGoods(inValue);
            strErr = retVal.strErr;
            return retVal.GetXlqBillGoodsResult;
        }
        
        public System.Threading.Tasks.Task<M_hmw.CIService.GetXlqBillGoodsResponse> GetXlqBillGoodsAsync(M_hmw.CIService.GetXlqBillGoodsRequest request) {
            return base.Channel.GetXlqBillGoodsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_hmw.CIService.GetXlqEntrustResponse M_hmw.CIService.CIServiceSoap.GetXlqEntrust(M_hmw.CIService.GetXlqEntrustRequest request) {
            return base.Channel.GetXlqEntrust(request);
        }
        
        public System.Data.DataTable GetXlqEntrust(string strUser, string strPW, string strTerm, out string strErr) {
            M_hmw.CIService.GetXlqEntrustRequest inValue = new M_hmw.CIService.GetXlqEntrustRequest();
            inValue.strUser = strUser;
            inValue.strPW = strPW;
            inValue.strTerm = strTerm;
            M_hmw.CIService.GetXlqEntrustResponse retVal = ((M_hmw.CIService.CIServiceSoap)(this)).GetXlqEntrust(inValue);
            strErr = retVal.strErr;
            return retVal.GetXlqEntrustResult;
        }
        
        public System.Threading.Tasks.Task<M_hmw.CIService.GetXlqEntrustResponse> GetXlqEntrustAsync(M_hmw.CIService.GetXlqEntrustRequest request) {
            return base.Channel.GetXlqEntrustAsync(request);
        }
        
        public string AlterXlqSys(string strUser, string strPW, System.Data.DataTable dtBillGoods, string[] strParas, string strCGNo, string strCargoNo, string strNewState, string strOldState) {
            return base.Channel.AlterXlqSys(strUser, strPW, dtBillGoods, strParas, strCGNo, strCargoNo, strNewState, strOldState);
        }
        
        public System.Threading.Tasks.Task<string> AlterXlqSysAsync(string strUser, string strPW, System.Data.DataTable dtBillGoods, string[] strParas, string strCGNo, string strCargoNo, string strNewState, string strOldState) {
            return base.Channel.AlterXlqSysAsync(strUser, strPW, dtBillGoods, strParas, strCGNo, strCargoNo, strNewState, strOldState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_hmw.CIService.GetLedStaticInfoResponse M_hmw.CIService.CIServiceSoap.GetLedStaticInfo(M_hmw.CIService.GetLedStaticInfoRequest request) {
            return base.Channel.GetLedStaticInfo(request);
        }
        
        public string GetLedStaticInfo(string strCodeDept, string strUser, string strPW, out string strErr) {
            M_hmw.CIService.GetLedStaticInfoRequest inValue = new M_hmw.CIService.GetLedStaticInfoRequest();
            inValue.strCodeDept = strCodeDept;
            inValue.strUser = strUser;
            inValue.strPW = strPW;
            M_hmw.CIService.GetLedStaticInfoResponse retVal = ((M_hmw.CIService.CIServiceSoap)(this)).GetLedStaticInfo(inValue);
            strErr = retVal.strErr;
            return retVal.GetLedStaticInfoResult;
        }
        
        public System.Threading.Tasks.Task<M_hmw.CIService.GetLedStaticInfoResponse> GetLedStaticInfoAsync(M_hmw.CIService.GetLedStaticInfoRequest request) {
            return base.Channel.GetLedStaticInfoAsync(request);
        }
        
        public string UpdateLedStaticInfo(string strCodeDept, string strUser, string strPW, string strNewLedInfo) {
            return base.Channel.UpdateLedStaticInfo(strCodeDept, strUser, strPW, strNewLedInfo);
        }
        
        public System.Threading.Tasks.Task<string> UpdateLedStaticInfoAsync(string strCodeDept, string strUser, string strPW, string strNewLedInfo) {
            return base.Channel.UpdateLedStaticInfoAsync(strCodeDept, strUser, strPW, strNewLedInfo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        M_hmw.CIService.GetWorkDriverResponse M_hmw.CIService.CIServiceSoap.GetWorkDriver(M_hmw.CIService.GetWorkDriverRequest request) {
            return base.Channel.GetWorkDriver(request);
        }
        
        public System.Data.DataTable GetWorkDriver(string strCodeDept, string strUser, string strPW, out string strErr) {
            M_hmw.CIService.GetWorkDriverRequest inValue = new M_hmw.CIService.GetWorkDriverRequest();
            inValue.strCodeDept = strCodeDept;
            inValue.strUser = strUser;
            inValue.strPW = strPW;
            M_hmw.CIService.GetWorkDriverResponse retVal = ((M_hmw.CIService.CIServiceSoap)(this)).GetWorkDriver(inValue);
            strErr = retVal.strErr;
            return retVal.GetWorkDriverResult;
        }
        
        public System.Threading.Tasks.Task<M_hmw.CIService.GetWorkDriverResponse> GetWorkDriverAsync(M_hmw.CIService.GetWorkDriverRequest request) {
            return base.Channel.GetWorkDriverAsync(request);
        }
        
        public string UpdateWorkDriver(string strUser, string strPW, System.Data.DataTable dtDriver) {
            return base.Channel.UpdateWorkDriver(strUser, strPW, dtDriver);
        }
        
        public System.Threading.Tasks.Task<string> UpdateWorkDriverAsync(string strUser, string strPW, System.Data.DataTable dtDriver) {
            return base.Channel.UpdateWorkDriverAsync(strUser, strPW, dtDriver);
        }
    }
}
