//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace M_hmw.HMWServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HMWServiceReference.ServiceHMWSoap")]
    public interface ServiceHMWSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelJinRiTouTiaoList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelJinRiTouTiaoList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelJinRiTouTiaoList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelJinRiTouTiaoListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelGangKouYaoWenList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelGangKouYaoWenList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelGangKouYaoWenList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelGangKouYaoWenListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelLuQiaoZiXunList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelLuQiaoZiXunList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelLuQiaoZiXunList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelLuQiaoZiXunListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelHangYeGuanChaList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelHangYeGuanChaList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelHangYeGuanChaList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelHangYeGuanChaListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelChuanBoZiXunList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelChuanBoZiXunList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelChuanBoZiXunList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelChuanBoZiXunListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelJiZhuangXiangChuanQiList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelJiZhuangXiangChuanQiList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelJiZhuangXiangChuanQiList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelJiZhuangXiangChuanQiListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelYunJiaList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelYunJiaList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelYunJiaList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelYunJiaListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelZaSanChuanQiList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelZaSanChuanQiList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelZaSanChuanQiList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelZaSanChuanQiListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelZaSanYunJiaList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelZaSanYunJiaList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelZaSanYunJiaList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelZaSanYunJiaListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelZaiBoChuanList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelZaiBoChuanList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelZaiBoChuanList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelZaiBoChuanListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMaoDiChuanList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMaoDiChuanList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMaoDiChuanList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMaoDiChuanListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelTieLuZiXunList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelTieLuZiXunList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelTieLuZiXunList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelTieLuZiXunListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelLaiGangHuoCheQueBaoList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelLaiGangHuoCheQueBaoList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelLaiGangHuoCheQueBaoList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelLaiGangHuoCheQueBaoListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMaTouXieCheJiHuaList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMaTouXieCheJiHuaList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMaTouXieCheJiHuaList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMaTouXieCheJiHuaListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMaTouZhuangCheJiHuaList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMaTouZhuangCheJiHuaList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMaTouZhuangCheJiHuaList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMaTouZhuangCheJiHuaListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelGongLuZiXunList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelGongLuZiXunList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelGongLuZiXunList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelGongLuZiXunListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelYiFangXingCheLiangList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelYiFangXingCheLiangList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelYiFangXingCheLiangList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelYiFangXingCheLiangListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelWangShangCheYuanList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelWangShangCheYuanList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelWangShangCheYuanList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelWangShangCheYuanListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelSiJiXinXiList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelSiJiXinXiList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelSiJiXinXiList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelSiJiXinXiListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelNeiHeZiXunList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelNeiHeZiXunList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelNeiHeZiXunList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelNeiHeZiXunListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelGuanHeGuoJiQueBaoChuanList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelGuanHeGuoJiQueBaoChuanList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelGuanHeGuoJiQueBaoChuanList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelGuanHeGuoJiQueBaoChuanListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelXinYunTaiQueBaoChuanList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelXinYunTaiQueBaoChuanList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelXinYunTaiQueBaoChuanList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelXinYunTaiQueBaoChuanListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelGuanHeGuoJiBoWeiChuanList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelGuanHeGuoJiBoWeiChuanList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelGuanHeGuoJiBoWeiChuanList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelGuanHeGuoJiBoWeiChuanListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelXinYunTaiBoWeiChuanList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelXinYunTaiBoWeiChuanList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelXinYunTaiBoWeiChuanList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelXinYunTaiBoWeiChuanListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelGuoJiMeiJiaoZiXunList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelGuoJiMeiJiaoZiXunList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelGuoJiMeiJiaoZiXunList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelGuoJiMeiJiaoZiXunListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelGuoNeiMeiJiaoZiXunList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelGuoNeiMeiJiaoZiXunList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelGuoNeiMeiJiaoZiXunList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelGuoNeiMeiJiaoZiXunListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelGangKouMeiJiaoZiXunList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelGangKouMeiJiaoZiXunList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelGangKouMeiJiaoZiXunList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelGangKouMeiJiaoZiXunListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMeiJiaoGongYingList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMeiJiaoGongYingList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMeiJiaoGongYingList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMeiJiaoGongYingListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMeiJiaoQiuGouList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMeiJiaoQiuGouList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMeiJiaoQiuGouList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMeiJiaoQiuGouListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMeiJiaoHangQingList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMeiJiaoHangQingList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMeiJiaoHangQingList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMeiJiaoHangQingListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelJiaoTanHangQingList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelJiaoTanHangQingList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelJiaoTanHangQingList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelJiaoTanHangQingListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelYouSeKuangZiXunList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelYouSeKuangZiXunList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelYouSeKuangZiXunList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelYouSeKuangZiXunListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelYouSeKuangGongQiuList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelYouSeKuangGongQiuList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelYouSeKuangGongQiuList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelYouSeKuangGongQiuListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelYouSeKuangHangQingList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelYouSeKuangHangQingList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelYouSeKuangHangQingList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelYouSeKuangHangQingListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelTieKuangShaZiXunList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelTieKuangShaZiXunList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelTieKuangShaZiXunList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelTieKuangShaZiXunListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelTieKuangShaGongQiuList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelTieKuangShaGongQiuList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelTieKuangShaGongQiuList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelTieKuangShaGongQiuListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelTieKuangShaHangQingList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelTieKuangShaHangQingList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelTieKuangShaHangQingList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelTieKuangShaHangQingListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelCangChuZiXunList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelCangChuZiXunList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelCangChuZiXunList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelCangChuZiXunListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelYuanQuCangChuList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelYuanQuCangChuList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelYuanQuCangChuList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelYuanQuCangChuListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelDaiChuHuoYuanList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelDaiChuHuoYuanList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelDaiChuHuoYuanList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelDaiChuHuoYuanListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelLaiGangQueBaoList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelLaiGangQueBaoList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelLaiGangQueBaoList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelLaiGangQueBaoListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyYuBaoChuanList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMyYuBaoChuanList(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyYuBaoChuanList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMyYuBaoChuanListAsync(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyQueBaoChuanList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMyQueBaoChuanList(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyQueBaoChuanList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMyQueBaoChuanListAsync(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyYinHangFeiList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMyYinHangFeiList(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyYinHangFeiList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMyYinHangFeiListAsync(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyGaoPingHuaFeiList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMyGaoPingHuaFeiList(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyGaoPingHuaFeiList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMyGaoPingHuaFeiListAsync(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyBoWeiChuanBoList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMyBoWeiChuanBoList(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyBoWeiChuanBoList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMyBoWeiChuanBoListAsync(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyChuanBoJiHuaList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMyChuanBoJiHuaList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyChuanBoJiHuaList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMyChuanBoJiHuaListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyYeWuWeiTuoYouChuanList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMyYeWuWeiTuoYouChuanList(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyYeWuWeiTuoYouChuanList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMyYeWuWeiTuoYouChuanListAsync(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyYeWuWeiTuoWuChuanList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMyYeWuWeiTuoWuChuanList(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyYeWuWeiTuoWuChuanList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMyYeWuWeiTuoWuChuanListAsync(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyZuoYeWeiTuoList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMyZuoYeWeiTuoList(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyZuoYeWeiTuoList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMyZuoYeWeiTuoListAsync(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyPiaoHuoList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMyPiaoHuoList(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyPiaoHuoList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMyPiaoHuoListAsync(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyHuoWuJinGangList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMyHuoWuJinGangList(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyHuoWuJinGangList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMyHuoWuJinGangListAsync(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyHuoWuChuGangList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMyHuoWuChuGangList(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyHuoWuChuGangList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMyHuoWuChuGangListAsync(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyHuoWuJieCunList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMyHuoWuJieCunList(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyHuoWuJieCunList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMyHuoWuJieCunListAsync(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyFeiYongJieSuanList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMyFeiYongJieSuanList(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyFeiYongJieSuanList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMyFeiYongJieSuanListAsync(string clientCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyYeWuShiXiangList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMyYeWuShiXiangList(string departmentCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyYeWuShiXiangList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMyYeWuShiXiangListAsync(string departmentCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyYiFuZhangDanList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMyYiFuZhangDanList(string departmentCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyYiFuZhangDanList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMyYiFuZhangDanListAsync(string departmentCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyGeRenXinXiList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMyGeRenXinXiList(string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyGeRenXinXiList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMyGeRenXinXiListAsync(string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyChuanDaiHuoDaiList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChannelMyChuanDaiHuoDaiList(string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannelMyChuanDaiHuoDaiList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetChannelMyChuanDaiHuoDaiListAsync(string userCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceHMWSoapChannel : M_hmw.HMWServiceReference.ServiceHMWSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceHMWSoapClient : System.ServiceModel.ClientBase<M_hmw.HMWServiceReference.ServiceHMWSoap>, M_hmw.HMWServiceReference.ServiceHMWSoap {
        
        public ServiceHMWSoapClient() {
        }
        
        public ServiceHMWSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceHMWSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHMWSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHMWSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string GetChannelJinRiTouTiaoList() {
            return base.Channel.GetChannelJinRiTouTiaoList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelJinRiTouTiaoListAsync() {
            return base.Channel.GetChannelJinRiTouTiaoListAsync();
        }
        
        public string GetChannelGangKouYaoWenList() {
            return base.Channel.GetChannelGangKouYaoWenList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelGangKouYaoWenListAsync() {
            return base.Channel.GetChannelGangKouYaoWenListAsync();
        }
        
        public string GetChannelLuQiaoZiXunList() {
            return base.Channel.GetChannelLuQiaoZiXunList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelLuQiaoZiXunListAsync() {
            return base.Channel.GetChannelLuQiaoZiXunListAsync();
        }
        
        public string GetChannelHangYeGuanChaList() {
            return base.Channel.GetChannelHangYeGuanChaList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelHangYeGuanChaListAsync() {
            return base.Channel.GetChannelHangYeGuanChaListAsync();
        }
        
        public string GetChannelChuanBoZiXunList() {
            return base.Channel.GetChannelChuanBoZiXunList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelChuanBoZiXunListAsync() {
            return base.Channel.GetChannelChuanBoZiXunListAsync();
        }
        
        public string GetChannelJiZhuangXiangChuanQiList() {
            return base.Channel.GetChannelJiZhuangXiangChuanQiList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelJiZhuangXiangChuanQiListAsync() {
            return base.Channel.GetChannelJiZhuangXiangChuanQiListAsync();
        }
        
        public string GetChannelYunJiaList() {
            return base.Channel.GetChannelYunJiaList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelYunJiaListAsync() {
            return base.Channel.GetChannelYunJiaListAsync();
        }
        
        public string GetChannelZaSanChuanQiList() {
            return base.Channel.GetChannelZaSanChuanQiList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelZaSanChuanQiListAsync() {
            return base.Channel.GetChannelZaSanChuanQiListAsync();
        }
        
        public string GetChannelZaSanYunJiaList() {
            return base.Channel.GetChannelZaSanYunJiaList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelZaSanYunJiaListAsync() {
            return base.Channel.GetChannelZaSanYunJiaListAsync();
        }
        
        public string GetChannelZaiBoChuanList() {
            return base.Channel.GetChannelZaiBoChuanList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelZaiBoChuanListAsync() {
            return base.Channel.GetChannelZaiBoChuanListAsync();
        }
        
        public string GetChannelMaoDiChuanList() {
            return base.Channel.GetChannelMaoDiChuanList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMaoDiChuanListAsync() {
            return base.Channel.GetChannelMaoDiChuanListAsync();
        }
        
        public string GetChannelTieLuZiXunList() {
            return base.Channel.GetChannelTieLuZiXunList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelTieLuZiXunListAsync() {
            return base.Channel.GetChannelTieLuZiXunListAsync();
        }
        
        public string GetChannelLaiGangHuoCheQueBaoList() {
            return base.Channel.GetChannelLaiGangHuoCheQueBaoList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelLaiGangHuoCheQueBaoListAsync() {
            return base.Channel.GetChannelLaiGangHuoCheQueBaoListAsync();
        }
        
        public string GetChannelMaTouXieCheJiHuaList() {
            return base.Channel.GetChannelMaTouXieCheJiHuaList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMaTouXieCheJiHuaListAsync() {
            return base.Channel.GetChannelMaTouXieCheJiHuaListAsync();
        }
        
        public string GetChannelMaTouZhuangCheJiHuaList() {
            return base.Channel.GetChannelMaTouZhuangCheJiHuaList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMaTouZhuangCheJiHuaListAsync() {
            return base.Channel.GetChannelMaTouZhuangCheJiHuaListAsync();
        }
        
        public string GetChannelGongLuZiXunList() {
            return base.Channel.GetChannelGongLuZiXunList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelGongLuZiXunListAsync() {
            return base.Channel.GetChannelGongLuZiXunListAsync();
        }
        
        public string GetChannelYiFangXingCheLiangList() {
            return base.Channel.GetChannelYiFangXingCheLiangList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelYiFangXingCheLiangListAsync() {
            return base.Channel.GetChannelYiFangXingCheLiangListAsync();
        }
        
        public string GetChannelWangShangCheYuanList() {
            return base.Channel.GetChannelWangShangCheYuanList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelWangShangCheYuanListAsync() {
            return base.Channel.GetChannelWangShangCheYuanListAsync();
        }
        
        public string GetChannelSiJiXinXiList() {
            return base.Channel.GetChannelSiJiXinXiList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelSiJiXinXiListAsync() {
            return base.Channel.GetChannelSiJiXinXiListAsync();
        }
        
        public string GetChannelNeiHeZiXunList() {
            return base.Channel.GetChannelNeiHeZiXunList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelNeiHeZiXunListAsync() {
            return base.Channel.GetChannelNeiHeZiXunListAsync();
        }
        
        public string GetChannelGuanHeGuoJiQueBaoChuanList() {
            return base.Channel.GetChannelGuanHeGuoJiQueBaoChuanList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelGuanHeGuoJiQueBaoChuanListAsync() {
            return base.Channel.GetChannelGuanHeGuoJiQueBaoChuanListAsync();
        }
        
        public string GetChannelXinYunTaiQueBaoChuanList() {
            return base.Channel.GetChannelXinYunTaiQueBaoChuanList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelXinYunTaiQueBaoChuanListAsync() {
            return base.Channel.GetChannelXinYunTaiQueBaoChuanListAsync();
        }
        
        public string GetChannelGuanHeGuoJiBoWeiChuanList() {
            return base.Channel.GetChannelGuanHeGuoJiBoWeiChuanList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelGuanHeGuoJiBoWeiChuanListAsync() {
            return base.Channel.GetChannelGuanHeGuoJiBoWeiChuanListAsync();
        }
        
        public string GetChannelXinYunTaiBoWeiChuanList() {
            return base.Channel.GetChannelXinYunTaiBoWeiChuanList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelXinYunTaiBoWeiChuanListAsync() {
            return base.Channel.GetChannelXinYunTaiBoWeiChuanListAsync();
        }
        
        public string GetChannelGuoJiMeiJiaoZiXunList() {
            return base.Channel.GetChannelGuoJiMeiJiaoZiXunList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelGuoJiMeiJiaoZiXunListAsync() {
            return base.Channel.GetChannelGuoJiMeiJiaoZiXunListAsync();
        }
        
        public string GetChannelGuoNeiMeiJiaoZiXunList() {
            return base.Channel.GetChannelGuoNeiMeiJiaoZiXunList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelGuoNeiMeiJiaoZiXunListAsync() {
            return base.Channel.GetChannelGuoNeiMeiJiaoZiXunListAsync();
        }
        
        public string GetChannelGangKouMeiJiaoZiXunList() {
            return base.Channel.GetChannelGangKouMeiJiaoZiXunList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelGangKouMeiJiaoZiXunListAsync() {
            return base.Channel.GetChannelGangKouMeiJiaoZiXunListAsync();
        }
        
        public string GetChannelMeiJiaoGongYingList() {
            return base.Channel.GetChannelMeiJiaoGongYingList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMeiJiaoGongYingListAsync() {
            return base.Channel.GetChannelMeiJiaoGongYingListAsync();
        }
        
        public string GetChannelMeiJiaoQiuGouList() {
            return base.Channel.GetChannelMeiJiaoQiuGouList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMeiJiaoQiuGouListAsync() {
            return base.Channel.GetChannelMeiJiaoQiuGouListAsync();
        }
        
        public string GetChannelMeiJiaoHangQingList() {
            return base.Channel.GetChannelMeiJiaoHangQingList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMeiJiaoHangQingListAsync() {
            return base.Channel.GetChannelMeiJiaoHangQingListAsync();
        }
        
        public string GetChannelJiaoTanHangQingList() {
            return base.Channel.GetChannelJiaoTanHangQingList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelJiaoTanHangQingListAsync() {
            return base.Channel.GetChannelJiaoTanHangQingListAsync();
        }
        
        public string GetChannelYouSeKuangZiXunList() {
            return base.Channel.GetChannelYouSeKuangZiXunList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelYouSeKuangZiXunListAsync() {
            return base.Channel.GetChannelYouSeKuangZiXunListAsync();
        }
        
        public string GetChannelYouSeKuangGongQiuList() {
            return base.Channel.GetChannelYouSeKuangGongQiuList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelYouSeKuangGongQiuListAsync() {
            return base.Channel.GetChannelYouSeKuangGongQiuListAsync();
        }
        
        public string GetChannelYouSeKuangHangQingList() {
            return base.Channel.GetChannelYouSeKuangHangQingList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelYouSeKuangHangQingListAsync() {
            return base.Channel.GetChannelYouSeKuangHangQingListAsync();
        }
        
        public string GetChannelTieKuangShaZiXunList() {
            return base.Channel.GetChannelTieKuangShaZiXunList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelTieKuangShaZiXunListAsync() {
            return base.Channel.GetChannelTieKuangShaZiXunListAsync();
        }
        
        public string GetChannelTieKuangShaGongQiuList() {
            return base.Channel.GetChannelTieKuangShaGongQiuList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelTieKuangShaGongQiuListAsync() {
            return base.Channel.GetChannelTieKuangShaGongQiuListAsync();
        }
        
        public string GetChannelTieKuangShaHangQingList() {
            return base.Channel.GetChannelTieKuangShaHangQingList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelTieKuangShaHangQingListAsync() {
            return base.Channel.GetChannelTieKuangShaHangQingListAsync();
        }
        
        public string GetChannelCangChuZiXunList() {
            return base.Channel.GetChannelCangChuZiXunList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelCangChuZiXunListAsync() {
            return base.Channel.GetChannelCangChuZiXunListAsync();
        }
        
        public string GetChannelYuanQuCangChuList() {
            return base.Channel.GetChannelYuanQuCangChuList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelYuanQuCangChuListAsync() {
            return base.Channel.GetChannelYuanQuCangChuListAsync();
        }
        
        public string GetChannelDaiChuHuoYuanList() {
            return base.Channel.GetChannelDaiChuHuoYuanList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelDaiChuHuoYuanListAsync() {
            return base.Channel.GetChannelDaiChuHuoYuanListAsync();
        }
        
        public string GetChannelLaiGangQueBaoList() {
            return base.Channel.GetChannelLaiGangQueBaoList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelLaiGangQueBaoListAsync() {
            return base.Channel.GetChannelLaiGangQueBaoListAsync();
        }
        
        public string GetChannelMyYuBaoChuanList(string clientCode) {
            return base.Channel.GetChannelMyYuBaoChuanList(clientCode);
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMyYuBaoChuanListAsync(string clientCode) {
            return base.Channel.GetChannelMyYuBaoChuanListAsync(clientCode);
        }
        
        public string GetChannelMyQueBaoChuanList(string clientCode) {
            return base.Channel.GetChannelMyQueBaoChuanList(clientCode);
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMyQueBaoChuanListAsync(string clientCode) {
            return base.Channel.GetChannelMyQueBaoChuanListAsync(clientCode);
        }
        
        public string GetChannelMyYinHangFeiList(string clientCode) {
            return base.Channel.GetChannelMyYinHangFeiList(clientCode);
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMyYinHangFeiListAsync(string clientCode) {
            return base.Channel.GetChannelMyYinHangFeiListAsync(clientCode);
        }
        
        public string GetChannelMyGaoPingHuaFeiList(string clientCode) {
            return base.Channel.GetChannelMyGaoPingHuaFeiList(clientCode);
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMyGaoPingHuaFeiListAsync(string clientCode) {
            return base.Channel.GetChannelMyGaoPingHuaFeiListAsync(clientCode);
        }
        
        public string GetChannelMyBoWeiChuanBoList(string clientCode) {
            return base.Channel.GetChannelMyBoWeiChuanBoList(clientCode);
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMyBoWeiChuanBoListAsync(string clientCode) {
            return base.Channel.GetChannelMyBoWeiChuanBoListAsync(clientCode);
        }
        
        public string GetChannelMyChuanBoJiHuaList() {
            return base.Channel.GetChannelMyChuanBoJiHuaList();
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMyChuanBoJiHuaListAsync() {
            return base.Channel.GetChannelMyChuanBoJiHuaListAsync();
        }
        
        public string GetChannelMyYeWuWeiTuoYouChuanList(string clientCode) {
            return base.Channel.GetChannelMyYeWuWeiTuoYouChuanList(clientCode);
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMyYeWuWeiTuoYouChuanListAsync(string clientCode) {
            return base.Channel.GetChannelMyYeWuWeiTuoYouChuanListAsync(clientCode);
        }
        
        public string GetChannelMyYeWuWeiTuoWuChuanList(string clientCode) {
            return base.Channel.GetChannelMyYeWuWeiTuoWuChuanList(clientCode);
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMyYeWuWeiTuoWuChuanListAsync(string clientCode) {
            return base.Channel.GetChannelMyYeWuWeiTuoWuChuanListAsync(clientCode);
        }
        
        public string GetChannelMyZuoYeWeiTuoList(string clientCode) {
            return base.Channel.GetChannelMyZuoYeWeiTuoList(clientCode);
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMyZuoYeWeiTuoListAsync(string clientCode) {
            return base.Channel.GetChannelMyZuoYeWeiTuoListAsync(clientCode);
        }
        
        public string GetChannelMyPiaoHuoList(string clientCode) {
            return base.Channel.GetChannelMyPiaoHuoList(clientCode);
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMyPiaoHuoListAsync(string clientCode) {
            return base.Channel.GetChannelMyPiaoHuoListAsync(clientCode);
        }
        
        public string GetChannelMyHuoWuJinGangList(string clientCode) {
            return base.Channel.GetChannelMyHuoWuJinGangList(clientCode);
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMyHuoWuJinGangListAsync(string clientCode) {
            return base.Channel.GetChannelMyHuoWuJinGangListAsync(clientCode);
        }
        
        public string GetChannelMyHuoWuChuGangList(string clientCode) {
            return base.Channel.GetChannelMyHuoWuChuGangList(clientCode);
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMyHuoWuChuGangListAsync(string clientCode) {
            return base.Channel.GetChannelMyHuoWuChuGangListAsync(clientCode);
        }
        
        public string GetChannelMyHuoWuJieCunList(string clientCode) {
            return base.Channel.GetChannelMyHuoWuJieCunList(clientCode);
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMyHuoWuJieCunListAsync(string clientCode) {
            return base.Channel.GetChannelMyHuoWuJieCunListAsync(clientCode);
        }
        
        public string GetChannelMyFeiYongJieSuanList(string clientCode) {
            return base.Channel.GetChannelMyFeiYongJieSuanList(clientCode);
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMyFeiYongJieSuanListAsync(string clientCode) {
            return base.Channel.GetChannelMyFeiYongJieSuanListAsync(clientCode);
        }
        
        public string GetChannelMyYeWuShiXiangList(string departmentCode) {
            return base.Channel.GetChannelMyYeWuShiXiangList(departmentCode);
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMyYeWuShiXiangListAsync(string departmentCode) {
            return base.Channel.GetChannelMyYeWuShiXiangListAsync(departmentCode);
        }
        
        public string GetChannelMyYiFuZhangDanList(string departmentCode) {
            return base.Channel.GetChannelMyYiFuZhangDanList(departmentCode);
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMyYiFuZhangDanListAsync(string departmentCode) {
            return base.Channel.GetChannelMyYiFuZhangDanListAsync(departmentCode);
        }
        
        public string GetChannelMyGeRenXinXiList(string userCode) {
            return base.Channel.GetChannelMyGeRenXinXiList(userCode);
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMyGeRenXinXiListAsync(string userCode) {
            return base.Channel.GetChannelMyGeRenXinXiListAsync(userCode);
        }
        
        public string GetChannelMyChuanDaiHuoDaiList(string userCode) {
            return base.Channel.GetChannelMyChuanDaiHuoDaiList(userCode);
        }
        
        public System.Threading.Tasks.Task<string> GetChannelMyChuanDaiHuoDaiListAsync(string userCode) {
            return base.Channel.GetChannelMyChuanDaiHuoDaiListAsync(userCode);
        }
    }
}
